name: Deploy to EC2 on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up SSH credentials manually
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PEM_FILE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EC2_HOST_KEY }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Optional: Verify SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -o ConnectTimeout=15 ec2-user@${{ secrets.EC2_HOST }} "echo SSH Connection Successful"

      # 3. Deploy to EC2 via SSH
      - name: Deploy to EC2
        env:
          DEMO_MODE: ${{ secrets.DEMO_MODE }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -o ConnectTimeout=15 ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Starting deployment..."

            # Navigate to the application directory
            cd /home/ec2-user/Caching-Server || { echo "Directory not found"; exit 1; }

            # Pull the latest code
            git fetch origin master
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/master)

            if [ "$LOCAL" = "$REMOTE" ]; then
              echo "Already up to date."
            else
              git pull origin master
            fi

            # Build the project
            mvn clean install

            # Stop any existing application instance safely
            echo "Stopping existing application..."
            pkill -f 'java -jar' || echo "No existing application process found."

            # Wait to ensure processes have been stopped
            sleep 5

            # Start the new application instance with a secure configuration
            echo "Starting new application..."
            nohup java -Dfile.encoding=UTF-8 -jar target/*.jar > app.log 2>&1 &

            echo "Deployment completed successfully."
          EOF
