name: Deploy to EC2 on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up SSH key and known hosts
      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PEM_FILE }}" > ~/.ssh/Github-Action-1.pem
          chmod 600 ~/.ssh/Github-Action-1.pem
          # Add EC2 host to known_hosts to bypass host verification
          ssh-keyscan -H ec2-50-17-144-60.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      # Optional: Test SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/Github-Action-1.pem ec2-user@ec2-50-17-144-60.compute-1.amazonaws.com "echo SSH Connection Successful"

      # 3. Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/Github-Action-1.pem ec2-user@ec2-50-17-144-60.compute-1.amazonaws.com << 'EOF'
            set -e

            echo "Starting deployment..."

            # Export environment variables
            export DEMO_MODE="${{ secrets.DEMO_MODE }}"
            export COINGECKO_API_KEY="${{ secrets.COINGECKO_API_KEY }}"

            # Navigate to the application directory
            cd /home/ec2-user/Caching-Server || { echo "Directory not found"; exit 1; }

            # Pull the latest code
            git fetch origin master
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/master)

            if [ "$LOCAL" = "$REMOTE" ]; then
              echo "Already up to date."
            else
              git pull origin master
            fi

            # Build the project
            mvn clean install

            # Stop any existing application instance safely
            echo "Stopping existing application..."
            pkill -f 'java -jar' || echo "No existing application process found."

            # Wait to ensure processes have been stopped
            sleep 5

            # Start the new application instance with environment variables
            echo "Starting new application..."
            nohup java -Dfile.encoding=UTF-8 -jar target/*.jar > app.log 2>&1 &

            echo "Deployment completed successfully."
          EOF
