name: Deploy to EC2 on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up SSH key with restrictive permissions
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PEM_FILE }}

      # 3. Manually add EC2 host key to known_hosts to prevent SSH authenticity prompts
      - name: Add EC2 Host Key Manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST_KEY }}" >> ~/.ssh/known_hosts

      # 4. Deploy to EC2 via SSH securely without hanging
      - name: Deploy to EC2
        env:
          DEMO_MODE: ${{ secrets.DEMO_MODE }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: |
          ssh -T -o StrictHostKeyChecking=yes ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Deploying application..."

            # Navigate to the application directory
            cd /home/ec2-user/Caching-Server || { echo "Directory not found"; exit 1; }

            # Pull the latest code
            if git fetch origin master && git status | grep -q 'up to date'; then
              echo "Already up to date."
            else
              git pull origin master
            fi

            # Build the project
            mvn clean install

            # Stop any existing application instance safely
            echo "Stopping existing application..."
            pkill -f 'java -jar' || echo "No existing application process found."

            # Wait to ensure processes have been stopped
            sleep 5

            # Start the new application instance with a secure configuration
            echo "Starting new application..."
            nohup java -Dfile.encoding=UTF-8 -jar target/*.jar > app.log 2>&1 &

            echo "Deployment completed successfully."
          EOF
