on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up SSH key and known hosts with retry logic for keyscan
      - name: Set up SSH key and known hosts
        run: |
          echo "Setting up SSH keys..."
          export HOME=/home/runner
          mkdir -p $HOME/.ssh
          
          # Save the SSH key
          echo "${{ secrets.PEM_FILE }}" | tr -d '\r' > $HOME/.ssh/Github-Action-1.pem
          chmod 400 $HOME/.ssh/Github-Action-1.pem
          
          # Start the SSH agent and add the key
          eval "$(ssh-agent -s)"
          ssh-add $HOME/.ssh/Github-Action-1.pem || { echo "Failed to add SSH key"; exit 1; }
          
          # Retry logic for ssh-keyscan to handle network issues
          for i in {1..10}; do
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts && break
            echo "ssh-keyscan attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done

          # Check if the known_hosts file contains the EC2 host
          if ! grep -q "${{ secrets.EC2_HOST }}" $HOME/.ssh/known_hosts; then
            echo "Failed to add EC2 host to known hosts after multiple attempts"
            exit 1
          fi

          chmod 644 $HOME/.ssh/known_hosts
          echo "SSH keys set up completed."

      # 3. SSH into EC2 instance and run commands directly in one SSH session
      - name: SSH into EC2 and execute deployment commands
        run: |
          echo "Connecting to EC2 instance and executing commands..."
          ssh -i $HOME/.ssh/Github-Action-1.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            echo "Connected to EC2 instance."

            # Stop existing Java application instance
            PID_FILE=/home/ec2-user/Caching-Server/app.pid
            if [ -f "$PID_FILE" ]; then
              PID=$(cat $PID_FILE)
              if ps -p $PID > /dev/null; then
                echo 'Stopping Java process with PID: ' $PID
                kill -15 $PID
                sleep 5
                if ps -p $PID > /dev/null; then
                  echo 'Force killing Java process...'
                  kill -9 $PID
                fi
                echo 'Java process stopped successfully.'
              else
                echo 'Java process is not running.'
              fi
              rm -f $PID_FILE
            else
              echo 'No PID file found. Skipping stop command.'
            fi

            # Deploy updated code
            echo 'Deploying the latest code...'
            cd /home/ec2-user/Caching-Server || { echo 'Directory not found'; exit 1; }

            echo 'Pulling latest code from Git...'
            git fetch origin master
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/master)
            if [ "$LOCAL" != "$REMOTE" ]; then
              git pull origin master || { echo 'Git pull failed'; exit 1; }
            else
              echo 'Already up to date.'
            fi

            echo 'Building the project...'
            mvn clean install || { echo 'Build failed'; exit 1; }

            # Start new Java application instance
            echo 'Starting new application instance...'

            # Define environment variables
            COINGECKO_REQUEST_DELAY_MS=15000
            COINGECKO_NUMBER_OF_BATCHES=4
            FETCH_COIN_INTERVAL_SECONDS=60
            UPDATE_DYNAMODB_INTERVAL_SECONDS=30
            DYNAMODB_WRITE_CAPACITY_UNITS=50

            nohup java -Dfile.encoding=UTF-8 \
              -Ddemo.mode="${{ secrets.DEMO_MODE }}" \
              -Dcoingecko.api.key="${{ secrets.COINGECKO_API_KEY }}" \
              -Dcoingecko.request.delay.ms=${COINGECKO_REQUEST_DELAY_MS} \
              -Dcoingecko.number.of.batches=${COINGECKO_NUMBER_OF_BATCHES} \
              -Dfetch.coin.interval.seconds=${FETCH_COIN_INTERVAL_SECONDS} \
              -Dupdate.dynamodb.interval.seconds=${UPDATE_DYNAMODB_INTERVAL_SECONDS} \
              -Ddynamodb.write.capacity.units=${DYNAMODB_WRITE_CAPACITY_UNITS} \
              -jar target/*.jar > app.log 2>&1 &

            echo $! > app.pid
            echo 'New application instance started successfully.'
          EOF
