name: Deploy to EC2 on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEMO_MODE: ${{ secrets.DEMO_MODE }}

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PEM_FILE }}

      # 3. Add EC2_HOST to known_hosts to prevent SSH authenticity prompts
      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4. Deploy to EC2 via SSH
      - name: Deploy to EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Deploying application..."

            # Export environment variables
            export DEMO_MODE=${{ secrets.DEMO_MODE }}

            # Navigate to the application directory
            cd /home/ec2-user/Caching-Server

            # Pull the latest code
            git pull origin master

            # Build the project
            mvn clean install

            # Stop any existing application instance
            echo "Stopping existing application..."
            pkill -f 'java -jar' || echo "No existing application process found."

            # Start the new application instance
            echo "Starting new application..."
            nohup java -jar target/*.jar > app.log 2>&1 &

            echo "Deployment completed successfully."
          EOF
